version: "3"
services:
  elasticsearch-astronomical:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.2
    container_name: elasticsearch-astronomical
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  kibana-astronomical:
    image: docker.elastic.co/kibana/kibana-oss:7.9.2
    container_name: kibana-astronomical
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch-astronomical:9200
    ports:
      - 5601:5601
  loader-astronomical:
    build: ./loader
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch-astronomical:9200
    depends_on:
      - elasticsearch-astronomical
      - kibana-astronomical
